queue_rules:
  - name: default
    merge_conditions:
      - check-success=check (macos-latest)
      - check-success=check (ubuntu-latest)
      # - check-success=buildbot/nix-build
    batch_size: 5
    merge_method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}
