name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: nix-community

      - name: Cargo test
        run: |
          mkdir -p ~/.config/nix-init
          echo "access-tokens.'github.com' = '$GITHUB_TOKEN'" > ~/.config/nix-init/config.toml
          nix develop -c cargo test e2e
        env:
          GITHUB_TOKEN: ${{ github.token }}
